
### SEND FETCH SONGS REQUEST
GET http://localhost:3000/songs/?page=1&limit=2

### Find SONGS REQUEST
GET http://localhost:3000/songs/2

### Create New SONGS REQUEST
POST http://localhost:3000/songs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IngxQGdtYWlsLmNvbSIsInVzZXJJZCI6NiwiYXJ0aXN0SWQiOjEsImlhdCI6MTc0OTExNDczNCwiZXhwIjoxNzQ5MjAxMTM0fQ.XQKYpXQnm3LKzHReFb9tUjIhk5BE8b9uHu-yWbhRQYc

{
  "title": "last",
  "releasedDate": "2024-09-29",
  "duration": "02:34",
  "artists": [
    1, 2
  ],
  "lyrics": "hello"
}


### Update SONGS REQUEST
PUT http://localhost:3000/songs/2
Content-Type: application/json

{
  "title": "last",
  "releasedDate": "2024-09-29",
  "duration": "02:34",
  "artists": ["single"],
  "lyrics": "hello"
}


### Update SONGS REQUEST
DELETE http://localhost:3000/songs/1

### Create new PlayList

POST http://localhost:3000/playlists
Content-Type: application/json

{
  "name": "Feel Good Now",
  "songs": [
    6
  ],
  "user": 2
}


### Signup User

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "firstName": "x1",
  "lastName": "doe",
  "email": "x1@gmail.com",
  "password": "123456"
}

### Login User

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "x1@gmail.com",
  "password": "123456"
}

### Profile

GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IngxQGdtYWlsLmNvbSIsInVzZXJJZCI6NiwiYXJ0aXN0SWQiOjEsImlhdCI6MTc0OTExNDczNCwiZXhwIjoxNzQ5MjAxMTM0fQ.XQKYpXQnm3LKzHReFb9tUjIhk5BE8b9uHu-yWbhRQYc

### Enable 2FA
GET http://localhost:3000/auth/enable-2fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IngxQGdtYWlsLmNvbSIsInVzZXJJZCI6NiwiYXJ0aXN0SWQiOjEsImlhdCI6MTc0OTExNDczNCwiZXhwIjoxNzQ5MjAxMTM0fQ.XQKYpXQnm3LKzHReFb9tUjIhk5BE8b9uHu-yWbhRQYc

### Validate 2FA Token
POST http://localhost:3000/auth/validate-2fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4xMkBnbWFpbC5jb20iLCJ1c2VySWQiOjEsImlhdCI6MTY4NDkxMTk3OCwiZXhwIjoxNjg0OTk4Mzc4fQ.qbBHZfu0VL_tY_bC2ccl1I_Xoc0IqG6wAk-D2-tZDa8
Content-Type: application/json

{
  "token": "993913"
}

### Disable 2FA
GET http://localhost:3000/auth/disable-2fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4xMkBnbWFpbC5jb20iLCJ1c2VySWQiOjEsImlhdCI6MTY4NDkxMTk3OCwiZXhwIjoxNjg0OTk4Mzc4fQ.qbBHZfu0VL_tY_bC2ccl1I_Xoc0IqG6wAk-D2-tZDa8
